version: '2.1'
services:
  webapp:
    environment:
      - SPRING_PROFILES_ACTIVE=prod
  elasticsearch:
    volumes:
      - esdata-prod:/usr/share/elasticsearch/data
volumes:
  esdata-prod:
    driver: local
