version: '2.1'
services:
  webapp:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      elasticsearch:
        condition: service_healthy
    healthcheck:
      test: wget --spider --quiet --tries=1 http://localhost:8080/actuator/info || exit 1
    image: ${IMAGE}:${VERSION}
    mem_limit: 1500m
    networks:
      - esnet
    ports:
      - 8080:8080
    restart: unless-stopped
  elasticsearch:
    environment:
      - cluster.name=policeticker
      - bootstrap.memory_lock=true
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - node.name=policeticker-1
      - network.host=0.0.0.0
      - discovery.type=single-node
      - discovery.zen.minimum_master_nodes=1
      - xpack.security.enabled=false
      - xpack.monitoring.enabled=false
      - xpack.ml.enabled=false
      - xpack.graph.enabled=false
      - xpack.watcher.enabled=false
    healthcheck:
      test: wget --spider --quiet --tries=1 http://localhost:9200 || exit 1
    image: docker.elastic.co/elasticsearch/elasticsearch:${ES_VERSION}
    mem_limit: 2g
    networks:
      - esnet
    ports:
      - 9200:9200
    restart: unless-stopped
    ulimits:
      memlock:
        soft: -1
        hard: -1
networks:
  esnet:
