version: '2.1'
services:
  webapp:
    build: .
    image: sepe81/lvz-viz:latest
    mem_limit: 1500m
    ports:
      - 8080:8080
    volumes:
      - ./data:/home/lvz-viz/data
    environment:
      - SPRING_PROFILES_ACTIVE=crawl
    healthcheck:
      test: wget --spider --quiet --tries=1 http://localhost:8080/health || exit 1
