FROM eclipse-temurin:21-jre-alpine

LABEL maintainer="Sebastian Peters <Sebastian.Peters@gmail.com>" \
      org.opencontainers.image.authors="Sebastian Peters <Sebastian.Peters@gmail.com>" \
      org.opencontainers.image.source="https://github.com/CodeforLeipzig/lvz-viz" \
      org.opencontainers.image.vendor="Open Knowledge Foundation Deutschland e.V."

# see https://github.com/adoptium/containers/blob/main/21/jdk/alpine/3.21/Dockerfile#L26
ENV LANG='de_DE.UTF-8' LANGUAGE='de_DE:de' LC_ALL='de_DE.UTF-8'

RUN echo "Europe/Berlin" > /etc/timezone

ENV USER=lvz-viz

RUN addgroup ${USER} \
  && adduser -D -G ${USER} -S ${USER}

USER ${USER}
WORKDIR /home/${USER}

COPY --chown=${USER} dewac_175m_600.crf.ser.gz .
# ordered from rarely to frequently changing, so a new commit only replaces the last layers
COPY --chown=${USER} build/extracted/dependencies/ ./app/
COPY --chown=${USER} build/extracted/spring-boot-loader/ ./app/
COPY --chown=${USER} build/extracted/frontend/ ./app/
COPY --chown=${USER} build/extracted/application/ ./app/

EXPOSE 8080

ENTRYPOINT ["java","-XshowSettings:vm","-XX:MaxRAMPercentage=95","-cp","./app","org.springframework.boot.loader.JarLauncher"]
