FROM adoptopenjdk/openjdk11:jre-11.0.3_7-alpine

LABEL maintainer="Sebastian Peters <Sebastian.Peters@gmail.com>"

ENV USER lvz-viz

RUN addgroup $USER \
  && adduser -D -G $USER -S $USER

USER $USER
WORKDIR /home/$USER

COPY --chown=lvz-viz dewac_175m_600.crf.ser.gz .
COPY --chown=lvz-viz build/libs/*.jar ./app.jar

EXPOSE 8080

ENTRYPOINT ["java","-XshowSettings:vm","-XX:MaxRAMPercentage=95","-Djava.security.egd=file:/dev/./urandom","-jar","./app.jar"]
