version: '2.1'
services:
  webapp:
    build:
      dockerfile: Dockerfile.dev
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    image: ${IMAGE}:${VERSION}-dev
  elasticsearch:
    volumes:
      - esdata-dev:/usr/share/elasticsearch/data
volumes:
  esdata-dev:
    driver: local
